version: "2"
services:
    db:
        image: mariadb:latest
        volumes:
            - wp_db_dev:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        links:
            - db
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./wordpress:/var/www/html
            - ./src/:/var/www/html/wp-content/themes/src/
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: wordpress

volumes:
    wp_db_dev:
        driver: local
